// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    routines,
    devices,
    groups,
  ];
  late final Shape0 routines = Shape0(
      source: i0.VersionedTable(
        entityName: 'routines',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 devices = Shape1(
      source: i0.VersionedTable(
        entityName: 'devices',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_26,
          _column_27,
          _column_13,
          _column_12,
          _column_14,
          _column_28,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 groups = Shape2(
      source: i0.VersionedTable(
        entityName: 'groups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_12,
          _column_13,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get monday =>
      columnsByName['monday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get tuesday =>
      columnsByName['tuesday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get wednesday =>
      columnsByName['wednesday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get thursday =>
      columnsByName['thursday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get friday =>
      columnsByName['friday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get saturday =>
      columnsByName['saturday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get sunday =>
      columnsByName['sunday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endTime =>
      columnsByName['end_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recurrence =>
      columnsByName['recurrence']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get changes =>
      columnsByName['changes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get groups =>
      columnsByName['groups']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get numBreaksTaken =>
      columnsByName['num_breaks_taken']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastBreakAt =>
      columnsByName['last_break_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get pausedUntil =>
      columnsByName['paused_until']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get maxBreaks =>
      columnsByName['max_breaks']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxBreakDuration =>
      columnsByName['max_break_duration']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get friction =>
      columnsByName['friction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get frictionLen =>
      columnsByName['friction_len']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get snoozedUntil =>
      columnsByName['snoozed_until']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get conditions =>
      columnsByName['conditions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get strictMode =>
      columnsByName['strict_mode']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>('id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_2(String aliasedName) =>
    i1.GeneratedColumn<bool>('monday', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("monday" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_3(String aliasedName) =>
    i1.GeneratedColumn<bool>('tuesday', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("tuesday" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_4(String aliasedName) =>
    i1.GeneratedColumn<bool>('wednesday', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("wednesday" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_5(String aliasedName) =>
    i1.GeneratedColumn<bool>('thursday', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("thursday" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_6(String aliasedName) =>
    i1.GeneratedColumn<bool>('friday', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("friday" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_7(String aliasedName) =>
    i1.GeneratedColumn<bool>('saturday', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("saturday" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_8(String aliasedName) =>
    i1.GeneratedColumn<bool>('sunday', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("sunday" IN (0, 1))'));
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('start_time', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('end_time', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>('recurrence', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>('changes', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_13(String aliasedName) =>
    i1.GeneratedColumn<bool>('deleted', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("deleted" IN (0, 1))'));
i1.GeneratedColumn<DateTime> _column_14(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('updated_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('groups', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>('num_breaks_taken', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<DateTime> _column_17(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_break_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_18(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('paused_until', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('max_breaks', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>('max_break_duration', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>('friction', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>('friction_len', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<DateTime> _column_23(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('snoozed_until', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>('conditions', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_25(String aliasedName) =>
    i1.GeneratedColumn<bool>('strict_mode', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("strict_mode" IN (0, 1))'));

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get curr =>
      columnsByName['curr']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get changes =>
      columnsByName['changes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get lastPulledAt =>
      columnsByName['last_pulled_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_27(String aliasedName) =>
    i1.GeneratedColumn<bool>('curr', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('CHECK ("curr" IN (0, 1))'));
i1.GeneratedColumn<DateTime> _column_28(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('last_pulled_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get device =>
      columnsByName['device']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get allow =>
      columnsByName['allow']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get apps =>
      columnsByName['apps']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sites =>
      columnsByName['sites']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categories =>
      columnsByName['categories']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get changes =>
      columnsByName['changes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('device', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('REFERENCES devices (id)'));
i1.GeneratedColumn<bool> _column_31(String aliasedName) =>
    i1.GeneratedColumn<bool>('allow', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('CHECK ("allow" IN (0, 1))'));
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>('apps', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>('sites', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>('categories', aliasedName, false,
        type: i1.DriftSqlType.string);

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    routines,
    devices,
    groups,
  ];
  late final Shape3 routines = Shape3(
      source: i0.VersionedTable(
        entityName: 'routines',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_35,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 devices = Shape1(
      source: i0.VersionedTable(
        entityName: 'devices',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_26,
          _column_27,
          _column_13,
          _column_12,
          _column_14,
          _column_28,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 groups = Shape2(
      source: i0.VersionedTable(
        entityName: 'groups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_29,
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_12,
          _column_13,
          _column_14,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get monday =>
      columnsByName['monday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get tuesday =>
      columnsByName['tuesday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get wednesday =>
      columnsByName['wednesday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get thursday =>
      columnsByName['thursday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get friday =>
      columnsByName['friday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get saturday =>
      columnsByName['saturday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get sunday =>
      columnsByName['sunday']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endTime =>
      columnsByName['end_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recurrence =>
      columnsByName['recurrence']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get changes =>
      columnsByName['changes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get groups =>
      columnsByName['groups']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get numBreaksTaken =>
      columnsByName['num_breaks_taken']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get lastBreakAt =>
      columnsByName['last_break_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get pausedUntil =>
      columnsByName['paused_until']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get maxBreaks =>
      columnsByName['max_breaks']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxBreakDuration =>
      columnsByName['max_break_duration']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get friction =>
      columnsByName['friction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get frictionLen =>
      columnsByName['friction_len']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get snoozedUntil =>
      columnsByName['snoozed_until']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get conditions =>
      columnsByName['conditions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get strictMode =>
      columnsByName['strict_mode']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get completableBefore =>
      columnsByName['completable_before']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>('completable_before', aliasedName, true,
        type: i1.DriftSqlType.int);
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
    ));
